import { readFileSync } from 'node:fs';
import { readdir, readFile, stat } from 'node:fs/promises';
import { extname, join, resolve } from 'node:path';

import type {
  AnalysisOptions,
  FileQualityReport,
  FunctionQualityReport,
  Grade,
  GradeDistribution,
  ProjectQualityReport,
} from './types.js';

// ─── Native binding loader ────────────────────────────────────────────────────

let _binding: { analyzeSource: (src: string, name: string, opts?: string) => string; quickScore: (src: string, name: string) => string } | null = null;

function getBinding() {
  if (_binding) return _binding;

  // Try the platform-aware loader (generated by napi build / qualitas_ts.js)
  try {
    _binding = require('../qualitas_ts.js');
    return _binding!;
  } catch {
    // fall through to manual platform detection
  }

  // Try platform-specific npm packages
  const platforms = [
    `@qualitas-ts/binding-${process.platform}-${process.arch}`,
    // Fallbacks with libc suffix
    `@qualitas-ts/binding-${process.platform}-${process.arch}-gnu`,
    `@qualitas-ts/binding-${process.platform}-${process.arch}-msvc`,
  ];

  for (const pkg of platforms) {
    try {
      _binding = require(pkg);
      return _binding!;
    } catch {
      // try next
    }
  }

  throw new Error(
    'qualitas-ts: No native binding found. ' +
    'Install the package via npm to get pre-built binaries, ' +
    'or run `npm run build` in the package root to build from source.'
  );
}

// ─── Default options ──────────────────────────────────────────────────────────

const DEFAULT_EXTENSIONS = ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'];
const DEFAULT_EXCLUDE = ['node_modules', 'dist', 'build', '.git', 'coverage'];
const TEST_PATTERNS = ['.test.', '.spec.', '.playwright-test.'];

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Analyze a TypeScript/JavaScript source string directly.
 * Useful for agent/automation use cases without file I/O.
 */
export function analyzeSource(
  source: string,
  fileName = 'anonymous.ts',
  options: AnalysisOptions = {}
): FileQualityReport {
  const binding = getBinding();
  const optsJson = JSON.stringify(options);
  const json = binding.analyzeSource(source, fileName, optsJson);
  return JSON.parse(json) as FileQualityReport;
}

/**
 * Analyze a single file by path.
 */
export async function analyzeFile(
  filePath: string,
  options: AnalysisOptions = {}
): Promise<FileQualityReport> {
  const source = await readFile(filePath, 'utf8');
  const report = analyzeSource(source, filePath, options);
  // Backfill file path into location objects
  for (const fn_ of report.functions) fn_.location.file = filePath;
  for (const cls of report.classes) {
    cls.location.file = filePath;
    for (const m of cls.methods) m.location.file = filePath;
  }
  return report;
}

/**
 * Analyze all TypeScript/JavaScript files in a directory recursively.
 */
export async function analyzeProject(
  dirPath: string,
  options: AnalysisOptions = {}
): Promise<ProjectQualityReport> {
  const extensions = options.extensions ?? DEFAULT_EXTENSIONS;
  const excludePatterns = [...DEFAULT_EXCLUDE, ...(options.exclude ?? [])];
  const includeTests = options.includeTests ?? false;

  const files = await collectFiles(resolve(dirPath), extensions, excludePatterns, includeTests);
  const fileReports = await Promise.all(files.map(f => analyzeFile(f, options)));

  return buildProjectReport(dirPath, fileReports, options);
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

async function collectFiles(
  dir: string,
  extensions: string[],
  exclude: string[],
  includeTests: boolean
): Promise<string[]> {
  const results: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (exclude.some(ex => entry.name === ex || entry.name.startsWith('.'))) continue;

    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      const sub = await collectFiles(full, extensions, exclude, includeTests);
      results.push(...sub);
    } else if (entry.isFile()) {
      const ext = extname(entry.name);
      if (!extensions.includes(ext)) continue;
      if (!includeTests && TEST_PATTERNS.some(p => entry.name.includes(p))) continue;
      results.push(full);
    }
  }
  return results;
}

function buildProjectReport(
  dirPath: string,
  fileReports: FileQualityReport[],
  options: AnalysisOptions
): ProjectQualityReport {
  const threshold = options.refactoringThreshold ?? 65;

  const allFunctions: FunctionQualityReport[] = [];
  for (const fr of fileReports) {
    allFunctions.push(...fr.functions);
    for (const cls of fr.classes) allFunctions.push(...cls.methods);
  }

  const totalWeight = allFunctions.reduce((sum, f) => sum + Math.max(f.metrics.structural.loc, 1), 0);
  const weightedScore = totalWeight > 0
    ? allFunctions.reduce((sum, f) => sum + f.score * Math.max(f.metrics.structural.loc, 1), 0) / totalWeight
    : 100;

  const dist: GradeDistribution = { a: 0, b: 0, c: 0, d: 0, f: 0 };
  for (const f of allFunctions) {
    dist[f.grade.toLowerCase() as keyof GradeDistribution]++;
  }

  const worstFunctions = [...allFunctions]
    .sort((a, b) => a.score - b.score)
    .slice(0, 10);

  const grade = scoreToGrade(weightedScore);

  return {
    dirPath,
    score: weightedScore,
    grade,
    needsRefactoring: weightedScore < threshold,
    files: fileReports,
    summary: {
      totalFiles: fileReports.length,
      totalFunctions: allFunctions.length,
      totalClasses: fileReports.reduce((s, f) => s + f.classCount, 0),
      flaggedFiles: fileReports.filter(f => f.needsRefactoring).length,
      flaggedFunctions: allFunctions.filter(f => f.needsRefactoring).length,
      averageScore: weightedScore,
      gradeDistribution: dist,
    },
    worstFunctions,
  };
}

function scoreToGrade(score: number): Grade {
  if (score >= 80) return 'A';
  if (score >= 65) return 'B';
  if (score >= 50) return 'C';
  if (score >= 35) return 'D';
  return 'F';
}

// Re-export all types
export type * from './types.js';
