import { readdir, readFile } from 'node:fs/promises';
import { extname, join, resolve } from 'node:path';

import type {
  AnalysisOptions,
  FlagConfig,
  FileQualityReport,
  FunctionQualityReport,
  Grade,
  GradeDistribution,
  ProjectQualityReport,
  QualitasConfig,
  QuickScore,
} from './types.js';
import { loadConfig, mergeOptions } from './config.js';

// ─── Native binding loader ────────────────────────────────────────────────────

let _binding: {
  analyzeSource: (src: string, name: string, opts?: string) => string;
  quickScore: (src: string, name: string) => string;
} | null = null;

function getBinding() {
  if (_binding) return _binding;

  // Try the platform-aware loader (generated by napi build / qualitas_napi.js)
  try {
    _binding = require('../qualitas_napi.js');
    return _binding!;
  } catch {
    // fall through to manual platform detection
  }

  // Try platform-specific npm packages
  const platforms = [
    `@qualitas/binding-${process.platform}-${process.arch}`,
    // Fallbacks with libc suffix
    `@qualitas/binding-${process.platform}-${process.arch}-gnu`,
    `@qualitas/binding-${process.platform}-${process.arch}-msvc`,
  ];

  for (const pkg of platforms) {
    try {
      _binding = require(pkg);
      return _binding!;
    } catch {
      // try next
    }
  }

  throw new Error(
    'qualitas: No native binding found. ' +
      'Install the package via npm to get pre-built binaries, ' +
      'or run `npm run build` in the package root to build from source.',
  );
}

// ─── Default options ──────────────────────────────────────────────────────────

const DEFAULT_EXTENSIONS = ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.py', '.pyi'];
// Only .git is universally excluded — all other excludes come from qualitas.config.js.
const DEFAULT_EXCLUDE = ['.git'];
const TEST_PATTERNS = ['.test.', '.spec.', '.playwright-test.'];

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Fast quality check — returns composite score, grade, refactoring flag, and top flags.
 * Faster than `analyzeSource` when you only need the summary (skips full metric breakdown).
 */
export function quickScore(source: string, fileName = 'anonymous.ts'): QuickScore {
  const binding = getBinding();
  return JSON.parse(binding.quickScore(source, fileName)) as QuickScore;
}

/**
 * Analyze a TypeScript/JavaScript/Python source string directly.
 * Useful for agent/automation use cases without file I/O.
 */
export function analyzeSource(
  source: string,
  fileName = 'anonymous.ts',
  options: AnalysisOptions = {},
): FileQualityReport {
  const binding = getBinding();
  const optsJson = JSON.stringify(options);
  const json = binding.analyzeSource(source, fileName, optsJson);
  return JSON.parse(json) as FileQualityReport;
}

/**
 * Analyze a single file by path.
 */
export async function analyzeFile(
  filePath: string,
  options: AnalysisOptions = {},
): Promise<FileQualityReport> {
  const source = await readFile(filePath, 'utf8');
  const report = analyzeSource(source, filePath, options);
  // Backfill file path into location objects
  if (report.fileScope) report.fileScope.location.file = filePath;
  for (const fn_ of report.functions) fn_.location.file = filePath;
  for (const cls of report.classes) {
    cls.location.file = filePath;
    for (const m of cls.methods) m.location.file = filePath;
  }
  return report;
}

/**
 * Analyze all supported source files in a directory recursively.
 */
export async function analyzeProject(
  dirPath: string,
  options: AnalysisOptions = {},
): Promise<ProjectQualityReport> {
  const config = loadConfig(resolve(dirPath));
  const mergedOpts = mergeOptions(config, options);
  const files = await collectProjectFiles(dirPath, mergedOpts, config);
  const fileReports = await analyzeFiles(files, mergedOpts, config);
  return buildProjectReport(dirPath, fileReports, mergedOpts);
}

async function collectProjectFiles(
  dirPath: string,
  opts: AnalysisOptions,
  config: QualitasConfig,
): Promise<string[]> {
  return collectFiles(resolve(dirPath), {
    extensions: opts.extensions ?? DEFAULT_EXTENSIONS,
    exclude: opts.exclude ?? DEFAULT_EXCLUDE,
    includeTests: opts.includeTests ?? false,
    testPatterns: resolveTestPatterns(config),
  });
}

function resolveTestPatterns(config: import('./types.js').QualitasConfig): string[] {
  const patterns = [...TEST_PATTERNS];
  const tsConfig = config.languages?.typescript;
  if (tsConfig?.testPatterns) return tsConfig.testPatterns;
  const pyConfig = config.languages?.python;
  if (pyConfig?.testPatterns) patterns.push(...pyConfig.testPatterns);
  return patterns;
}

async function analyzeFiles(
  files: string[],
  mergedOpts: AnalysisOptions,
  config: QualitasConfig,
): Promise<FileQualityReport[]> {
  return Promise.all(
    files.map((f) => {
      const flagOverrides = resolveFlagOverrides(f, config);
      const opts = flagOverrides ? { ...mergedOpts, flagOverrides } : mergedOpts;
      return analyzeFile(f, opts);
    }),
  );
}

// ─── Flag config resolution ───────────────────────────────────────────────

function languageForExtension(filePath: string): string | null {
  const ext = extname(filePath).slice(1); // remove leading dot
  switch (ext) {
    case 'ts':
    case 'tsx':
    case 'js':
    case 'jsx':
    case 'mjs':
    case 'cjs':
      return 'typescript';
    case 'rs':
      return 'rust';
    case 'py':
    case 'pyi':
      return 'python';
    default:
      return null;
  }
}

function resolveFlagOverrides(
  filePath: string,
  config: QualitasConfig,
): Record<string, FlagConfig> | undefined {
  const globalFlags = config.flags;
  const lang = languageForExtension(filePath);
  const langFlags = lang ? config.languages?.[lang]?.flags : undefined;

  if (!globalFlags && !langFlags) return undefined;
  if (globalFlags && !langFlags) return globalFlags;
  if (!globalFlags && langFlags) return langFlags;
  return { ...globalFlags, ...langFlags };
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function isExcludedEntry(name: string, exclude: string[]): boolean {
  return exclude.some((ex) => name === ex || name.startsWith('.'));
}

function isMatchingSourceFile(
  name: string,
  extensions: string[],
  includeTests: boolean,
  testPatterns: string[],
): boolean {
  const ext = extname(name);
  if (!extensions.includes(ext)) return false;
  if (!includeTests && testPatterns.some((p) => name.includes(p))) return false;
  return true;
}

interface WalkConfig {
  extensions: string[];
  exclude: string[];
  includeTests: boolean;
  testPatterns: string[];
}

async function walkDirectory(dir: string, config: WalkConfig, results: string[]): Promise<void> {
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    await processEntry(dir, entry, config, results);
  }
}

async function processEntry(
  dir: string,
  entry: { name: string; isDirectory(): boolean; isFile(): boolean },
  config: WalkConfig,
  results: string[],
): Promise<void> {
  if (isExcludedEntry(entry.name, config.exclude)) return;

  const full = join(dir, entry.name);
  if (entry.isDirectory()) {
    await walkDirectory(full, config, results);
  } else if (
    entry.isFile() &&
    isMatchingSourceFile(entry.name, config.extensions, config.includeTests, config.testPatterns)
  ) {
    results.push(full);
  }
}

async function collectFiles(dir: string, config: WalkConfig): Promise<string[]> {
  const results: string[] = [];
  await walkDirectory(dir, config, results);
  return results;
}

function collectAllFunctions(fileReports: FileQualityReport[]): FunctionQualityReport[] {
  const allFunctions: FunctionQualityReport[] = [];
  for (const fr of fileReports) {
    if (fr.fileScope) allFunctions.push(fr.fileScope);
    allFunctions.push(...fr.functions);
    for (const cls of fr.classes) allFunctions.push(...cls.methods);
  }
  return allFunctions;
}

function computeWeightedScore(allFunctions: FunctionQualityReport[]): number {
  const totalWeight = allFunctions.reduce(
    (sum, f) => sum + Math.max(f.metrics.structural.loc, 1),
    0,
  );
  return totalWeight > 0
    ? allFunctions.reduce((sum, f) => sum + f.score * Math.max(f.metrics.structural.loc, 1), 0) /
        totalWeight
    : 100;
}

function computeGradeDistribution(allFunctions: FunctionQualityReport[]): GradeDistribution {
  const dist: GradeDistribution = { a: 0, b: 0, c: 0, d: 0, f: 0 };
  for (const f of allFunctions) {
    dist[f.grade.toLowerCase() as keyof GradeDistribution]++;
  }
  return dist;
}

function findWorstFunctions(
  allFunctions: FunctionQualityReport[],
  count: number,
): FunctionQualityReport[] {
  return [...allFunctions].sort((a, b) => a.score - b.score).slice(0, count);
}

function buildProjectSummary(
  fileReports: FileQualityReport[],
  allFunctions: FunctionQualityReport[],
  score: number,
): ProjectQualityReport['summary'] {
  return {
    totalFiles: fileReports.length,
    totalFunctions: allFunctions.length,
    totalClasses: fileReports.reduce((s, f) => s + f.classCount, 0),
    flaggedFiles: fileReports.filter((f) => f.needsRefactoring).length,
    flaggedFunctions: allFunctions.filter((f) => f.needsRefactoring).length,
    averageScore: score,
    gradeDistribution: computeGradeDistribution(allFunctions),
  };
}

function buildProjectReport(
  dirPath: string,
  fileReports: FileQualityReport[],
  options: AnalysisOptions,
): ProjectQualityReport {
  const allFunctions = collectAllFunctions(fileReports);
  const score = computeWeightedScore(allFunctions);

  return {
    dirPath,
    score,
    grade: scoreToGrade(score),
    needsRefactoring: score < (options.refactoringThreshold ?? 65),
    files: fileReports,
    summary: buildProjectSummary(fileReports, allFunctions, score),
    worstFunctions: findWorstFunctions(allFunctions, 10),
  };
}

function scoreToGrade(score: number): Grade {
  if (score >= 80) return 'A';
  if (score >= 65) return 'B';
  if (score >= 50) return 'C';
  if (score >= 35) return 'D';
  return 'F';
}

// Re-export all types
export type * from './types.js';
