import type {
  FileQualityReport,
  FunctionQualityReport,
  Grade,
  ProjectQualityReport,
} from '../types.js';

function gradeBadge(grade: Grade): string {
  const colors: Record<Grade, string> = {
    A: 'brightgreen',
    B: 'blue',
    C: 'yellow',
    D: 'orange',
    F: 'red',
  };
  return `![Grade ${grade}](https://img.shields.io/badge/grade-${grade}-${colors[grade]})`;
}

function functionRow(fn: FunctionQualityReport): string {
  const flagIcons = fn.flags.map(f => {
    return f.severity === 'error' ? '🔴' : '🟡';
  }).join('');
  return `| \`${fn.name}\` | ${fn.score.toFixed(1)} | ${fn.grade} | ${fn.metrics.cognitiveFlow.score} | ${fn.metrics.dataComplexity.difficulty.toFixed(1)} | ${fn.metrics.identifierReference.totalIrc.toFixed(1)} | ${fn.metrics.structural.parameterCount} | ${fn.metrics.structural.loc} | ${flagIcons || '✅'} |`;
}

export function renderMarkdownReport(report: FileQualityReport): string {
  const lines: string[] = [];

  lines.push(`## qualitas-ts: \`${report.filePath}\``);
  lines.push('');
  lines.push(`**Quality Score:** ${report.score.toFixed(1)} / 100  ${gradeBadge(report.grade)}`);
  lines.push('');

  if (report.functions.length > 0) {
    lines.push('### Functions');
    lines.push('');
    lines.push('| Function | Score | Grade | CFC | DCI | IRC | Params | LOC | Status |');
    lines.push('|----------|-------|-------|-----|-----|-----|--------|-----|--------|');
    for (const fn of report.functions) {
      lines.push(functionRow(fn));
    }
    lines.push('');
  }

  const flagged = report.functions.filter(f => f.flags.length > 0);
  if (flagged.length > 0) {
    lines.push('### Refactoring Recommendations');
    lines.push('');
    for (const fn of flagged) {
      lines.push(`#### \`${fn.name}\` (score: ${fn.score.toFixed(1)})`);
      for (const flag of fn.flags) {
        const icon = flag.severity === 'error' ? '🔴' : '🟡';
        lines.push(`- ${icon} **${flag.message}**`);
        lines.push(`  - 💡 ${flag.suggestion}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Generated by [qualitas-ts](https://github.com/qualitas-ts/qualitas-ts)*`);

  return lines.join('\n');
}

export function renderMarkdownProjectReport(report: ProjectQualityReport): string {
  const lines: string[] = [];
  const s = report.summary;

  lines.push(`# qualitas-ts Report: \`${report.dirPath}\``);
  lines.push('');
  lines.push(`**Project Score:** ${report.score.toFixed(1)} / 100  ${gradeBadge(report.grade)}`);
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Files analyzed | ${s.totalFiles} |`);
  lines.push(`| Functions analyzed | ${s.totalFunctions} |`);
  lines.push(`| Functions needing refactoring | ${s.flaggedFunctions} |`);
  lines.push(`| Grade distribution | A:${s.gradeDistribution.a} B:${s.gradeDistribution.b} C:${s.gradeDistribution.c} D:${s.gradeDistribution.d} F:${s.gradeDistribution.f} |`);
  lines.push('');

  if (report.worstFunctions.length > 0) {
    lines.push('## Top Functions Needing Refactoring');
    lines.push('');
    lines.push('| Function | File | Score | Grade | Top Flag |');
    lines.push('|----------|------|-------|-------|----------|');
    for (const fn of report.worstFunctions) {
      const topFlag = fn.flags[0]?.message ?? '—';
      lines.push(`| \`${fn.name}\` | \`${fn.location.file}\` | ${fn.score.toFixed(1)} | ${fn.grade} | ${topFlag} |`);
    }
  }

  return lines.join('\n');
}
