use qualitas_core::types::{FileQualityReport, FunctionQualityReport, Grade, ProjectQualityReport};

fn grade_badge(grade: Grade) -> String {
    let color = match grade {
        Grade::A => "brightgreen",
        Grade::B => "blue",
        Grade::C => "yellow",
        Grade::D => "orange",
        Grade::F => "red",
    };
    format!("![Grade {grade}](https://img.shields.io/badge/grade-{grade}-{color})")
}

fn function_row(func: &FunctionQualityReport) -> String {
    let flag_icons: String = func
        .flags
        .iter()
        .map(|f| {
            if f.severity == qualitas_core::types::Severity::Error {
                "\u{1f534}"
            } else {
                "\u{1f7e1}"
            }
        })
        .collect();

    let status = if flag_icons.is_empty() {
        "\u{2705}".to_string()
    } else {
        flag_icons
    };

    format!(
        "| `{}` | {:.1} | {} | {} | {:.1} | {:.1} | {} | {} | {status} |",
        func.name,
        func.score,
        func.grade,
        func.metrics.cognitive_flow.score,
        func.metrics.data_complexity.difficulty,
        func.metrics.identifier_reference.total_irc,
        func.metrics.structural.parameter_count,
        func.metrics.structural.loc,
    )
}

pub fn render_markdown_report(report: &FileQualityReport) -> String {
    let mut lines: Vec<String> = Vec::new();

    lines.push(format!("## qualitas: `{}`", report.file_path));
    lines.push(String::new());
    lines.push(format!(
        "**Quality Score:** {:.1} / 100  {}",
        report.score,
        grade_badge(report.grade),
    ));
    lines.push(String::new());

    if !report.functions.is_empty() {
        lines.push("### Functions".to_string());
        lines.push(String::new());
        lines.push(
            "| Function | Score | Grade | CFC | DCI | IRC | Params | LOC | Status |".to_string(),
        );
        lines.push(
            "|----------|-------|-------|-----|-----|-----|--------|-----|--------|".to_string(),
        );
        for func in &report.functions {
            lines.push(function_row(func));
        }
        lines.push(String::new());
    }

    let flagged: Vec<&FunctionQualityReport> = report
        .functions
        .iter()
        .filter(|f| !f.flags.is_empty())
        .collect();
    if !flagged.is_empty() {
        lines.push("### Refactoring Recommendations".to_string());
        lines.push(String::new());
        for func in &flagged {
            lines.push(format!("#### `{}` (score: {:.1})", func.name, func.score));
            for flag in &func.flags {
                let icon = if flag.severity == qualitas_core::types::Severity::Error {
                    "\u{1f534}"
                } else {
                    "\u{1f7e1}"
                };
                lines.push(format!("- {icon} **{}**", flag.message));
                lines.push(format!("  - \u{1f4a1} {}", flag.suggestion));
            }
            lines.push(String::new());
        }
    }

    lines.push("---".to_string());
    lines.push("*Generated by [qualitas](https://github.com/qualitas-ts/qualitas-ts)*".to_string());

    lines.join("\n")
}

pub fn render_markdown_project_report(report: &ProjectQualityReport) -> String {
    let mut lines: Vec<String> = Vec::new();
    let s = &report.summary;

    lines.push(format!("# qualitas Report: `{}`", report.dir_path));
    lines.push(String::new());
    lines.push(format!(
        "**Project Score:** {:.1} / 100  {}",
        report.score,
        grade_badge(report.grade),
    ));
    lines.push(String::new());
    lines.push("| Metric | Value |".to_string());
    lines.push("|--------|-------|".to_string());
    lines.push(format!("| Files analyzed | {} |", s.total_files));
    lines.push(format!("| Functions analyzed | {} |", s.total_functions));
    lines.push(format!(
        "| Functions needing refactoring | {} |",
        s.flagged_functions
    ));
    lines.push(format!(
        "| Grade distribution | A:{} B:{} C:{} D:{} F:{} |",
        s.grade_distribution.a,
        s.grade_distribution.b,
        s.grade_distribution.c,
        s.grade_distribution.d,
        s.grade_distribution.f,
    ));
    lines.push(String::new());

    if !report.worst_functions.is_empty() {
        lines.push("## Top Functions Needing Refactoring".to_string());
        lines.push(String::new());
        lines.push("| Function | File | Score | Grade | Top Flag |".to_string());
        lines.push("|----------|------|-------|-------|----------|".to_string());
        for func in &report.worst_functions {
            let top_flag = func
                .flags
                .first()
                .map_or("\u{2014}".to_string(), |f| f.message.clone());
            lines.push(format!(
                "| `{}` | `{}` | {:.1} | {} | {top_flag} |",
                func.name, func.location.file, func.score, func.grade,
            ));
        }
    }

    lines.join("\n")
}
